//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestePraticoMVC_Fitcard.Models
{
    using System;
    using System.Collections.Generic;

    public partial class Estabelecimento
    {
        public int estabelecimentoID { get; set; }
        public int CategoriaID { get; set; }
        public Nullable<System.DateTime> dataCad { get; set; }
        public string razao { get; set; }
        public string fantasia { get; set; }
        public string CNPJ { get; set; }
        public string email { get; set; }
        public string endereco { get; set; }
        public string cidade { get; set; }
        public string estado { get; set; }
        public string telefone { get; set; }
        public string agencia { get; set; }
        public string conta { get; set; }
        public bool status { get; set; }
        public string labelCategoria { get; set; }
        public string labelStatus { get; set; }
    }
}
